### ISSUE TITLE
Code

### ISSUE THREAD

**Issue by Codeei** [zeng-ziyin/LACV_Net#1]
您好，请问完整的代码什么时候能上传呢？我尝试把C-VLAD添加到我的网络中，但是还是会报错，关于num_list未被定义的问题。

**Comment by zeng-ziyin** [comment]
我们已经上传了完整的LACV-Net.py文件在U-Next代码库中

**Comment by Codeei** [comment]
> 我们已经上传了完整的LACV-Net.py文件在U-Next代码库中

非常感谢 :）
